name: documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        
      # Using this approach to make it easier to integrate with cmake        
      - name: Run doxygen
        run: |
          if [ ! -d build ]; then mkdir build; fi
          if [ ! -d docs ]; then mkdir docs; fi
          touch docs/.dummy && echo "There is nothing here!" > docs/.dummy
          cd build
          doxygen ../Doxyfile.ini
          
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update documentation" -a
          
#       - name: Deploy
#         uses: s0/git-publish-subdir-action@develop
#         env:
#           REPO: self
#           BRANCH: gh-pages
#           FOLDER: docs
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           MESSAGE: Update documentation for commit {sha}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: docs
